---
- name: Installs unattended upgrades
  apt:
    name: unattended-upgrades
    state: present

- name: Blacklist packages
  template:
    src: 90unattended-blacklist.j2
    dest: /etc/apt/apt.conf.d/90unattended-blacklist
    owner: root
    group: root
    mode: 0640

- name: Adds upgrade config
  template:
    src: 20auto-upgrades.j2
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: 0640

- name: Unmask required targets for timers
  systemd:
    name: "{{ item }}"
    masked: false
  loop:
    - apt-daily-upgrade.service
    - apt-daily.service

- name: Enables and unmask required timers
  systemd:
    name: "{{ item }}"
    masked: false
    enabled: true
    state: started
  loop:
    - apt-daily-upgrade.timer
    - apt-daily.timer
